### DISCUSSION TITLE
Nested query for YAML based TinyDB table

### DISCUSSION THREAD

**Discussion by TheNewThinkTank** [msiemens/tinydb#554] [Q&A] [answered]
I am struggling with performing nested queries on my YAML based TinyDB table,
below are links to the data and code I am working on (an open source fitness-tracker for logging and analysing weight training).
To test out nested querying, I am querying the nested field "weights", if it contains the string "BODYWEIGHT" (which it does when inspected manually). The result is always an empty list, what am I missing here?
data:
[tmp.txt](https://github.com/msiemens/tinydb/files/14215139/tmp.txt)
script:
https://github.com/TheNewThinkTank/fitness-tracker/blob/main/src/CRUD/update.py#:~:text=func-,search_table,-func

**Comment by msiemens** [comment, marked as answer]
I guess you're using the YAMLStorage from https://tinydb.readthedocs.io/en/latest/extend.html?

In general, TinyDB is not particularly strong when searching a `dict` for an entry with a particular value. `Query.any` for example will run on a `dict`'s keys, not values. If you store your exercises as a list, you can easily find an entry with `weight` containing `BODYWEIGHT`:

```yml
weight_training_log:
  '188':
    date: '2024-01-07'
    start_time: '15:50'
    end_time: '16:22'
    timezone: CET
    split: push
    exercises:
      - type: incline_db_press
        sets:
        - set_number: 1
          reps: 8
          weight: 40 kg
        - set_number: 2
          reps: 10
          weight: 40 kg
        - set_number: 3
          reps: 8
          weight: 40 kg
      - type: db_incline_flys
        sets:
        - set_number: 1
          reps: 10
          weight: 28 kg
        - set_number: 2
          reps: 10
          weight: 28 kg
        - set_number: 3
          reps: 8
          weight: 28 kg
      - type: seated_db_shoulder_press
        sets:
        - set_number: 1
          reps: 10
          weight: 24 kg
        - set_number: 2
          reps: 10
          weight: 24 kg
        - set_number: 3
          reps: 10
          weight: 24 kg
      - type: behind_the_back_cable_lateral_raise
        sets:
        - set_number: 1
          reps: 12
          weight: 4.5 kg
        - set_number: 2
          reps: 12
          weight: 4.5 kg
        - set_number: 3
          reps: 12
          weight: 4.5 kg
      - type: seated_db_rear_lateral_raise
        sets:
        - set_number: 1
          reps: 12
          weight: 10 kg
        - set_number: 2
          reps: 12
          weight: 10 kg
        - set_number: 3
          reps: 12
          weight: 10 kg
      - type: static_hang
        sets:
        - set_number: 1
          reps: 1
          weight: BODYWEIGHT kg
          duration: 60 seconds
# ...
```

```python
db = TinyDB('test.yml', storage=YAMLStorage)
print(db.table('weight_training_log').search(where('exercises').any(where('sets').any(where('weight').search('BODYWEIGHT')))))
```
